# Created with YamlCreate.ps1 v2.2.4 $debug=NVS0.CRLF.7-2-10.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: LuculentSystems.AltA2DP
PackageVersion: 1.2.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2023-05-30
Installers:
- Architecture: x64
  InstallerUrl: https://www.bluetoothgoodies.com/a2dp/files/AlternativeA2dpSetup-1.2.0.1.msi
  InstallerSha256: 9BBF7459DB4E9AFCDB15B34527551A0A06711F0350832E31905692808446C69A
  ProductCode: '{753D2EA2-A262-493E-BBA6-AD4263E39104}'
ManifestType: installer
ManifestVersion: 1.4.0
